kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: submodules
    commands:
      - git submodule update --init --recursive

  - name: environnement
    commands:
      - ls -a /home/tonycava/
      - cp /home/tonycava/matchmaking/.env .

  - name: stop-previous-version
    commands:
      - docker-compose -f docker-compose.prod.yml down | true

  - name: deploy
    commands:
      - docker compose -f docker-compose.prod.yml up --build
