kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: submodules
    commands:
      - git submodule init
      - git submodule update --recursive --remote
      - cd backend/ && git checkout main && cd ..
      - cd frontend/ && git checkout main && cd ..

  - name: stop-previous-version
    commands:
      - docker compose -f docker-compose.prod.yml down | true

  - name: deploy
    commands:
      - docker compose -f docker-compose.prod.yml up -d --build

    environment:
      POSTGRES_PASSWORD:
        from_secret: POSTGRES_PASSWORD
      POSTGRES_USER:
        from_secret: POSTGRES_USER
      POSTGRES_DB:
        from_secret: POSTGRES_DB
      DATABASE_URL:
        from_secret: DATABASE_URL
      JWT_SECRET:
        from_secret: JWT_SECRET

      FRONT_END_PORT:
        from_secret: FRONT_END_PORT
      BACK_END_PORT:
        from_secret: BACK_END_PORT

      API_URL:
        from_secret: API_URL
      EXTERNAL_API_URL:
        from_secret: EXTERNAL_API_URL