kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: submodules
    commands:
      - git submodule update --init --recursive
      - cd back/ && git checkout main && cd ..
      - cd front/ && git checkout main && cd ..

  - name: environnement
    commands:
      - cp /home/tonycava/matchmaking/.env .

  - name: stop-previous-version
    commands:
      - docker-compose -f docker-compose.prod.yml down | true

  - name: deploy
    commands:
      - docker compose -f docker-compose.prod.yml up --build
