version: "3.7"

services:
  db:
    image: postgres:12.2-alpine
    container_name: matchmaking_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - matchmaking-vol:/var/lib/postgresql/data
    ports:
      - "11000:5432"

  front:
    container_name: matchmaking_front
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "11001:3000"
    volumes:
      - ./front/src:/app/src
      - ./front/static:/app/static
      - ./front/tailwind.config.cjs:/app/tailwind.config.cjs
      - ./.env:/app/.env

  back:
    container_name: matchmaking_back
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./back:/app
    ports:
      - "11002:${BACK_END_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PORT: ${BACK_END_PORT}
      JWT_SECRET: ${JWT_SECRET}

volumes:
  matchmaking-vol: