version: "3.7"

services:
  db:
    image: postgres:12.2-alpine
    container_name: matchmaking_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - matchmaking-vol:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - "11000:5432"

  front:
    container_name: matchmaking_front
    build:
      context: .
      dockerfile: frontend/Dockerfile.prod
    restart: always
    environment:
      PORT: ${FRONT_END_PORT}
      PUBLIC_API_URL: ${API_URL}
      PUBLIC_EXTERNAL_API_URL: ${EXTERNAL_API_URL}
      ENVIROMENT: ${ENVIRONMENT}
    ports:
      - "8089:3000"

  back:
    container_name: matchmaking_back
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    restart: always
    ports:
      - "8090:3000"
    environment:
      PORT: ${BACK_END_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      ENVIROMENT: ${ENVIRONMENT}


volumes:
  matchmaking-vol: