name: Cypress tests
on: [push]
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Re init project
        run: |
          rm -rf back/ front/
          git submodule update --force --recursive --init --remote
          cd front/ && git switch origin/$GITHUB_REF_NAME --detach

      - name: Install dependencies
        run: make install-dependencies

      - name: start web server
        run: |
          cd front/ && yarn run build
          cd ..
          make start-front-only &
        env:
          FRONT_END_PORT: 3000
          API_URL: http://back:3000
          EXTERNAL_API_URL: http://localhost:11002

      - name: wait for web server
        run: |
          while ! curl --output /dev/null --silent --head --fail http://localhost:11001; do
            printf '.'
            sleep 5
          done
          echo "Web server is up"

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./front
          browser: chrome
          record: false
          start: yarn run cy:run
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
