name: Cypress tests
on: [push]
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Re init project
        run: |
          rm -rf backend/ frontend/ shared/
          git submodule update --force --recursive --init --remote
          cd frontend/ && git switch origin/$GITHUB_REF_NAME --detach

      - name: start web server
        run: make start-prod
        env:
          FRONT_END_PORT: 3000
          API_URL: http://back:3000
          EXTERNAL_API_URL: http://localhost:8090
          BACK_END_PORT: 3000
          JWT_SECRET: secret
          BACK_END_DATABASE_URL: postgres://matchmaking:matchmaking@db:5432/matchmaking
          POSTGRES_USER: matchmaking
          POSTGRES_PASSWORD: matchmaking
          POSTGRES_DB: matchmaking
          ENVIRONMENT: test

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          wait-on: http://localhost:8089
          working-directory: ./frontend
          browser: electron
          record: true
          start: yarn run cy:run
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}